# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image with a slim variant
FROM python:3.13-slim

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml file and src directory into the container
COPY src /app/src
COPY requirements.lock /app/requirements.txt

# Install the dependencies specified in the pyproject.toml
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Set environment variables for LinkedIn credentials
# These should be set during container run or through a Docker secret mechanism
ENV LINKEDIN_CLIENT_ID=your_linkedin_client_id
ENV LINKEDIN_CLIENT_SECRET=your_linkedin_client_id
ENV LINKEDIN_ACCESS_TOKEN=your_linkedin_client_id
ENV LINKEDIN_REFRESH_TOKEN=your_linkedin_client_id
ENV PYTHONPATH=/app

# Set the entry point for the container
CMD ["python","-m", "src.mcp_linkedin.main"]