# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image with a slim variant
FROM python:3.13-slim

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml file and src directory into the container
COPY pyproject.toml /app/
COPY src /app/src
COPY requirements.lock /app/

# Install the dependencies specified in the pyproject.toml
RUN pip install --upgrade pip
RUN pip install -r requirements.lock

# Set environment variables for LinkedIn credentials
# These should be set during container run or through a Docker secret mechanism
ENV LINKEDIN_CLIENT_ID=your_linkedin_client_id
ENV LINKEDIN_CLIENT_SECRET=LINKEDIN_CLIENT_SECRET
ENV LINKEDIN_ACCESS_TOKEN=LINKEDIN_ACCESS_TOKEN
ENV LINKEDIN_REFRESH_TOKEN=LINKEDIN_REFRESH_TOKEN

# Set the entry point for the container
ENTRYPOINT ["uvicorn", "mcp_linkedin.client:mcp.run", "--host", "0.0.0.0", "--port", "8000"]