[project]
name = "mcp-linkedin"
version = "0.1.1"
description = "MCP server to interact with LinkedIn"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "linkedin-api",
    "fastmcp",
    "requests",
    "uvicorn",
]
